/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_mypicardo_facer_face_detection_mtcnn_business_OpenCvMtcnnFaceDetector */

#ifndef _Included_de_mypicardo_facer_face_detection_mtcnn_business_OpenCvMtcnnFaceDetector
#define _Included_de_mypicardo_facer_face_detection_mtcnn_business_OpenCvMtcnnFaceDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_mypicardo_facer_face_detection_mtcnn_business_OpenCvMtcnnFaceDetector
 * Method:    findFaces
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_mypicardo_facer_face_detection_mtcnn_business_OpenCvMtcnnFaceDetector_findFaces
  (JNIEnv *, jobject, jstring, jstring, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
