/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_mypicardo_facer_face_detection_business_OpenCvMtcnn */

#ifndef _Included_de_mypicardo_facer_face_detection_business_OpenCvMtcnn
#define _Included_de_mypicardo_facer_face_detection_business_OpenCvMtcnn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_mypicardo_facer_face_detection_business_OpenCvMtcnn
 * Method:    findFaces
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_mypicardo_facer_face_detection_business_OpenCvMtcnn_findFaces
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
